table dHora
	lineageTag: 95d04f5e-c102-4ef1-96a7-987f5dbb8dfd

	column Hora
		dataType: dateTime
		formatString: Long Time
		lineageTag: ce0efb10-023d-4f0e-b5e0-e69f13897371
		summarizeBy: none
		sourceColumn: Hora

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Hora Num'
		dataType: int64
		formatString: 0
		lineageTag: b03bfc8b-a3da-4e27-bdef-0e3b30a60064
		summarizeBy: none
		sourceColumn: Hora Num

		annotation SummarizationSetBy = Automatic

	column 'Minuto Num'
		dataType: int64
		formatString: 0
		lineageTag: 70098aaa-41bd-41c6-b5b3-4025fcf0f9a3
		summarizeBy: none
		sourceColumn: Minuto Num

		annotation SummarizationSetBy = Automatic

	column 'Segundo Num'
		dataType: int64
		formatString: 0
		lineageTag: e34623ad-cda2-4696-b824-796a986ff0ac
		summarizeBy: none
		sourceColumn: Segundo Num

		annotation SummarizationSetBy = Automatic

	column AMPM
		dataType: string
		lineageTag: 8f46fc37-fb53-455a-b395-c3ddbf652857
		summarizeBy: none
		sourceColumn: AMPM

		annotation SummarizationSetBy = Automatic

	column 'Hora AMPM'
		dataType: string
		lineageTag: ffe02e3a-9570-4590-94d9-4e7e1d1ac4a9
		summarizeBy: none
		sourceColumn: Hora AMPM

		annotation SummarizationSetBy = Automatic

	column Período
		dataType: string
		lineageTag: c086f89d-5368-4abf-b9e1-f0e11d4571f7
		summarizeBy: none
		sourceColumn: Período

		annotation SummarizationSetBy = Automatic

	column Turno
		dataType: string
		lineageTag: 26d790cd-8c0a-44ba-a8dc-b0c2e0bc8220
		summarizeBy: none
		sourceColumn: Turno

		annotation SummarizationSetBy = Automatic

	column 'Período Ordem'
		dataType: int64
		formatString: 0
		lineageTag: 5db404fe-1cd5-4162-9e65-1199fb3e2456
		summarizeBy: none
		sourceColumn: Período Ordem

		annotation SummarizationSetBy = Automatic

	partition dHora = m
		mode: import
		source = ```
				let
				    Lista = {0..86399},
				    ConverteParaTabela = Table.FromList(Lista, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    AlteraTipo = Table.TransformColumnTypes(ConverteParaTabela,{{"Column1", Int64.Type}}),
				    AlteraNomeCol = Table.RenameColumns(AlteraTipo,{{"Column1", "Segundo"}}),
				    ColDuracao = Table.AddColumn(AlteraNomeCol,"Duração", each #duration(0,0,0,[Segundo]), type duration),
				    ColHora = Table.AddColumn(ColDuracao, "Hora", each #time(Duration.Hours([Duração]),Duration.Minutes([Duração]),Duration.Seconds([Duração])), type time),
				    RemoveCols = Table.RemoveColumns(ColHora,{"Duração", "Segundo"}),
				    ColHoraNum = Table.AddColumn(RemoveCols, "Hora Num", each Time.Hour([Hora]), Int64.Type),
				    ColMinutoNum = Table.AddColumn(ColHoraNum, "Minuto Num", each Time.Minute([Hora]), Int64.Type),
				    ColSegundoNum = Table.AddColumn(ColMinutoNum, "Segundo Num", each Time.Second([Hora]), Int64.Type),
				    ColAMPM = Table.AddColumn(ColSegundoNum,"AMPM", each if [Hora Num] < 12 then "AM" else "PM", type text),
				    ColHoraAMPM = Table.AddColumn(ColAMPM, "Hora AMPM", each 
				        if [Hora Num] = 0 then "12 AM"
				        else if [Hora Num] >= 1 and [Hora Num] <= 11 then Number.ToText([Hora Num]) & " AM" 
				        else if [Hora Num] = 12 then "12 PM"
				        else if [Hora Num] >= 13 then Number.ToText([Hora Num] - 12) & " PM"  
				        else "Unknown", type text),
				    ColPeriodo = 
				        Table.AddColumn(ColHoraAMPM, "Período", each 
				            if        [Hora Num] >= 0 and [Hora Num] <= 5 then "12AM - 6AM"
				            else if   [Hora Num] >= 6 and [Hora Num] <= 11 then "6AM - 12PM"
				            else if   [Hora Num] >= 12 and [Hora Num] <= 17  then "12PM - 6PM"
				            else if   [Hora Num] >= 18 and [Hora Num] <= 23 then "6PM - 12AM"
				            else "Unknown", type text
				            ),
				    ColPeriodoTurno = 
				        Table.AddColumn(ColPeriodo, "Turno", each 
				            if        [Hora Num] >= 0 and [Hora Num] <= 5 then "Madrugada"
				            else if   [Hora Num] >= 6 and [Hora Num] <= 11 then "Manhã"
				            else if   [Hora Num] >= 12 and [Hora Num] <= 17  then "Tarde"
				            else if   [Hora Num] >= 18 and [Hora Num] <= 23 then "Noite"
				            else "Unknown", type text
				            ),
				    ColPeriodoOrdem = 
				        Table.AddColumn(ColPeriodoTurno, "Período Ordem", each 
				            if        [Hora Num] >= 0 and [Hora Num] <= 5 then 1
				            else if   [Hora Num] >= 6 and [Hora Num] <= 11 then 2
				            else if   [Hora Num] >= 12 and [Hora Num] <= 17  then 3
				            else if   [Hora Num] >= 18 and [Hora Num] <= 23 then 4
				            else 5, Int64.Type
				        )
				in
				    ColPeriodoOrdem
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

