table Medidas
	lineageTag: 591d39a0-0641-4496-944d-d1a906b46fbb

	measure 'Total Funcionarios' = ```
			
			CALCULATE(
			DISTINCTCOUNT(dFuncionarios[funcionarioid]), 
			  CROSSFILTER(fFolhaPagamento[funcionarioid],dFuncionarios[funcionarioid],Both)
			)
			```
		formatString: #,0
		lineageTag: ef38fc26-a779-45f6-889e-96b9fccbaf7a

	measure 'Salário Médio' = AVERAGE(fFolhaPagamento[salario_base])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: c63f2300-3577-44e1-bed5-483a85b5682a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Custo Saúde' = SUM(fFolhaPagamento[custo_plano_saude])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: b94b77d8-adbb-427d-81e2-9f160f08f930

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Salário' = sum(fFolhaPagamento[salario_base])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: fce27abf-e812-4a4f-965b-085704ee5ba3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Custo Total Folha' = [Total Salário] + [Custo Saúde]
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 6b2b206f-70a0-459a-9512-dc187496c75a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Media Horas' = AVERAGE(fPonto[horas_trabalhadas_decimal])
		lineageTag: 0bb44e19-2a9d-4516-92f1-23e9a4050676

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Ausencias' =
			
			
			CALCULATE(
			    COUNTROWS(fPonto),
			    fPonto[flag_ausencia] = "1"
			)
		formatString: 0
		lineageTag: cc1aa961-781b-4ff5-9c63-be54b7a06a24

	measure 'Registros incompletos' =
			
			
			CALCULATE(
			    COUNTROWS(fPonto),
			    fPonto[flag_registro_incompleto] = "1"
			)
		formatString: 0
		lineageTag: 68b1b97a-baaf-48ff-83e2-07ef9ef46c4c

	measure 'Absenteísmo %' =
			
			
			DIVIDE([Total Ausencias], COUNT(fPonto[pontoid]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 13844ecb-4f90-4ba3-bb4b-ce7006ec5256

	measure 'Custo Médio por Funcionário' =
			
			DIVIDE(
			    [Custo Total Folha],
			    [Total Funcionarios],
			    0
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: aa39fd73-ad24-43d8-801f-a24586af98c8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Horas Esperadas' = ```
			
			
			VAR DiasUteis = COUNTROWS(
			                  FILTER(fPonto, fPonto[flag_ausencia] = "0"
			                  )
			                )
			
			VAR JornadaDiaria = 8 
			
			RETURN DiasUteis * JornadaDiaria
			```
		formatString: 0
		lineageTag: 4ac4f5d2-28bb-467e-94de-237d6650e526

	measure 'Percentual Horas Cumpridas' =
			
			DIVIDE(
			    [Horas Trabalhadas Totais],
			    [Horas Esperadas],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a2315cb4-f334-46f5-abbe-b5b502938883

	measure 'Horas Trabalhadas Totais' =
			
			SUM(fPonto[horas_trabalhadas_decimal])
		formatString: 0
		lineageTag: f79b4e18-c133-46e5-9c20-fdd338d9dbf0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Top 5 Empresas - Custo' = ```
			
			VAR RankingEmpresas = 
			    ADDCOLUMNS(
			        VALUES(dEmpresa[nomeempresa]),
			        "@Custo", [Custo Total Folha]
			    )
			VAR Top5 = 
			    TOPN(5, RankingEmpresas, [@Custo], DESC)
			RETURN
			SUMX(Top5, [@Custo])
			```
		lineageTag: 5b2d5551-0270-442c-9e3c-5b185de81b65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Custo Plano sobre Folha' =
			
			DIVIDE(
			    [Custo Saúde],
			    [Custo Total Folha],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0bdf7ff0-58a7-42da-a331-cfd641509a51

	measure 'Custo Médio Plano Saúde' =
			
			AVERAGE(fFolhaPagamento[custo_plano_saude])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 09458a1a-483a-4583-b3a1-a34f4b5c2eaa

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '% Impacto no Custo Total' =
			
			VAR CustoEmpresaSelecionada = [Custo Total Folha]
			VAR CustoTotalDoGrupo = CALCULATE([Custo Total Folha], ALL(dEmpresa))
			RETURN
			DIVIDE(CustoEmpresaSelecionada, CustoTotalDoGrupo)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 82272e81-4f67-4eda-829d-b0496821f8e9

	measure 'Tendência Icone' =
			
			VAR MesAnterior = CALCULATE([Absenteísmo %], PREVIOUSMONTH(dCalendario[Data]))
			RETURN
			IF([Absenteísmo %] > MesAnterior, "▲", "▼")
		lineageTag: d4cb2861-04a0-47d5-a07c-ba3618107760

	column Value
		isHidden
		formatString: 0
		lineageTag: a3654feb-e3d8-4442-a125-f2fef4722704
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 5181e56de59848bcb8f21f6e34f67ef9

